language: c

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      compiler: gcc-5
      env: MY_BUILD_TYPE=debug
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      compiler: gcc-5
      env: MY_BUILD_TYPE=all
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      compiler: gcc-4.9
      env: MY_BUILD_TYPE=all
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - clang-3.9
      compiler: clang-3.9
      env: MY_BUILD_TYPE=all

script:
  - echo $MY_BUILD_TYPE
  - cmake --version
  - $CC --version
  - make $MY_BUILD_TYPE
