language: c

matrix:
  fast_finish: true

addons: &mydeps
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - cmake
      - cmake-data
      - $CC

matrix:
  include:
    - compiler: gcc-5
      addons: *mydeps
      env: MY_BUILD_TYPE=debug
    - compiler: gcc-5
      addons: *mydeps
      env: MY_BUILD_TYPE=all
    - compiler: gcc-4.9
      addons: *mydeps
      env: MY_BUILD_TYPE=all
    - compiler: clang-3.9
      addons: *mydeps
      env: MY_BUILD_TYPE=all

script:
  - echo $MY_BUILD_TYPE
  - cmake --version
  - $CC --version
  - make $MY_BUILD_TYPE
