language: c

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - gcc-4.9
      - gcc-4.8
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - clang-3.9
      - clang-3.8
      - clang-3.7

compiler:
  - gcc-5
  - gcc-4.9
  - gcc-4.8
  - clang-3.9
  - clang-3.8
  - clang-3.7

env:
  - MY_BUILD_TYPE=all
  - MY_BUILD_TYPE=debug

script:
  - echo $MY_BUILD_TYPE
  - make $MY_BUILD_TYPE
