language: c

cache:
  ccache: true
  apt: true
  directories:
    - sdl2install
    - SDL2-2.0.4

install:
  - export SDL2DIR="$(pwd)/sdl2install"
  - if [[ ! -f SDL2-2.0.4/configure ]]; then wget 'https://www.libsdl.org/release/SDL2-2.0.4.tar.gz'; tar xzf SDL2-2.0.4.tar.gz; fi
  - if [[ ! -f $SDL2DIR/include/SDL2/SDL.h ]]; then pushd SDL2-2.0.4; ./configure --prefix=$SDL2DIR; make; make install; popd; fi
  - export SDL2_DIR=$SDL2DIR/lib/cmake

addons: &mydeps
  apt:
    sources: &mysources
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages: &newcmake
      - cmake
      - cmake-data

matrix:
  fast_finish: true
  allow_failures:
    - env: MY_BUILD_TYPE=debug
  include:
    - compiler: gcc-5
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - gcc-5
      env:
        - MY_BUILD_TYPE=all
    - compiler: gcc-5
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - gcc-5
      env:
        - MY_BUILD_TYPE=debug
    - compiler: gcc-4.9
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - gcc-4.9
      env:
        - MY_BUILD_TYPE=all
    - compiler: clang-3.9
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - clang-3.9
      env:
        - MY_BUILD_TYPE=all

script:
  - echo $MY_BUILD_TYPE
  - echo $CMAKE_INCLUDE_PATH $CMAKE_LIBRARY_PATH
  - cmake --version
  - $CC --version
  - make $MY_BUILD_TYPE
