language: c

matrix:
  fast_finish: true

addons: &mydeps
  apt:
    sources: &mysources
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages: &newcmake
      - cmake
      - cmake-data

matrix:
  include:
    - compiler: gcc-5
      addons:
        sources: *mysources
        apt:
          packages:
            - *newcmake
            - gcc-5
      env: MY_BUILD_TYPE=debug
    - compiler: gcc-5
      addons:
        sources: *mysources
        apt:
          packages:
            - *newcmake
            - gcc-5
      env: MY_BUILD_TYPE=all
    - compiler: gcc-4.9
      addons:
        sources: *mysources
        apt:
          packages:
            - *newcmake
            - gcc-4.9
      env: MY_BUILD_TYPE=all
    - compiler: clang-3.9
      addons:
        sources: *mysources
        apt:
          packages:
            - *newcmake
            - clang-3.9
      env: MY_BUILD_TYPE=all

script:
  - echo $MY_BUILD_TYPE
  - cmake --version
  - $CC --version
  - env
  - make $MY_BUILD_TYPE
