language: c

matrix:
  fast_finish: true

#cache:
#  ccache: true
#  directories:
#    - sdl2install
#    - SDL2-2.0.4

install:
  - export SDL2DIR="$(pwd)/sdl2install"
  - if [[ ! -f SDL2-2.0.4/configure ]]; then wget 'https://www.libsdl.org/release/SDL2-2.0.4.tar.gz'; tar xzf SDL2-2.0.4.tar.gz; fi
  - if [[ ! -f sdl2install/include/SDL2/SDL.h ]]; then pushd SDL2-2.0.4; ./configure --prefix=$SDL2DIR; make; make install; popd; fi
  - ls -al $SDL2DIR/include
  - ls -al $SDL2DIR/lib
  - export CMAKE_INCLUDE_PATH=$SDL2DIR/include
  - export CMAKE_LIBRARY_PATH=$SDL2DIR/lib

addons: &mydeps
  apt:
    sources: &mysources
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages: &newcmake
      - cmake
      - cmake-data

matrix:
  include:
    - compiler: gcc-5
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - gcc-5
      env:
        - MY_BUILD_TYPE=debug
        - DIFFERENT_CACHE=gcc-5-debug
    - compiler: gcc-5
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - gcc-5
      env:
        - MY_BUILD_TYPE=all
        - DIFFERENT_CACHE=gcc-5-all
    - compiler: gcc-4.9
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - gcc-4.9
      env:
        - MY_BUILD_TYPE=all
        - DIFFERENT_CACHE=gcc-4.9-all
    - compiler: clang-3.9
      addons:
        apt:
          sources: *mysources
          packages:
            - *newcmake
            - clang-3.9
      env:
        - MY_BUILD_TYPE=all
        - DIFFERENT_CACHE=clang-3.9-all

script:
  - echo $MY_BUILD_TYPE
  - echo $CMAKE_INCLUDE_PATH $CMAKE_LIBRARY_PATH
  - cmake --version
  - $CC --version
  - make $MY_BUILD_TYPE
