version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015

environment:
  SDL2_LIBRARIES: SDL2-2.0.4/lib
  SDL2_INCLUDE_DIRS: SDL2-2.0.4/include

install:
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
  - dir
  - 7z x SDL2-devel-2.0.4-VC.zip
#  - set SDL2_LIBRARIES=SDL2-2.0.4/lib
#  - set SDL2_INCLUDE_DIRS=SDL2-2.0.4/include

build_script:
- cmd: |
    md build
    cd build
    cmake --version
    cmake -G"Visual Studio 14 2015 Win64" ..
    dir
    msbuild /m /p:Platform="Win64" Boids.Experiment.sln
