version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015

environment:
  SDL2_LIBRARIES: "/LIBPATH:SDL2-2.0.4\\lib /link SDL2"
  SDL2_INCLUDE_DIRS: SDL2-2.0.4/include

install:
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
  - dir
  - 7z x SDL2-devel-2.0.4-VC.zip

build_script:
- cmd: |
    cmake --version
    md build
    cd build
    cmake -G "Visual Studio 14 2015 Win64" --config Release ..
    msbuild Boids.Experiment.sln /p:Configuration=Release /p:Platform="x64" /m
